version: '3'

services:
  # -- Django container --
  srv_django:
    # vars are injected at runtime, so no need to specify env_var value here.
    image: 'python:3.12.0-bookworm'
    volumes:
      - ..:/workspaces:delegated
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    expose:
      - 8000

  # -- PostgreSQL container --
  srv_postgres:
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    image: 'postgres:15-bookworm'
    restart: unless-stopped
    volumes:
      - postgres-data-somename:/var/lib/postgresql/data
    expose:
      - 5432

  srv_redis:
    image: "redis:bookworm"
    restart: unless-stopped
    expose:
      - 6379


volumes:
  postgres-data-somename:
