version: '3'

services:

  srv_django:
    container_name: "mason_ctn_django"
    # vars are injected at runtime, so no need to specify env_var value here.
    image: 'python:3.12.0-bookworm'
    volumes:
      - ..:/workspaces:delegated
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    expose:
      - 8000

  srv_postgres:
    container_name: "mason_ctn_postgres"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    image: 'postgres:15-bookworm'
    restart: unless-stopped
    volumes:
      - postgres-data-mason:/var/lib/postgresql/data
    expose:
      - 5432

  srv_redis:
    container_name: "mason_ctn_redis"
    image: "redis:bookworm"
    restart: unless-stopped
    expose:
      - 6379

  srv_soketi:
    container_name: "mason_ctn_soketi"
    image: "quay.io/soketi/soketi:1.4-16-debian"
    expose:
      - 6001
      - 9601 # metrics

volumes:
  postgres-data-mason:
